### ISSUE TITLE
Minimap Misaligned

### ISSUE THREAD

**Issue by Grayfox2325** [KaiKorla/ElvUI_Enhanced_Again#3]
**Describe the bug**
This was always an issue, even with the old version, but hoping you can help. I have my minimap on the bottom of my screen, x-370, y0. Even at y0, the minimap is not properly aligned with the bottom of the screen. When I look at moving the anchors in Elvui, it's like the frame itself is misaligned with the minimap (frame starts a few pixels below the minimap, and ends a few pixels from the top). This drives me crazy, would love a way to fix the alignment.

**To Reproduce**
1. Move Minimap to bottom of screen
2. Go crazy as you can't reach the bottom of screen

**Expected behavior**

**Screenshots**
https://imgur.com/a/KmxO6cr

**Version (please complete the following information):**
 - Version ElvUI [13.76]
 - Version Elvui_Enhanced [5.1.1]

**Additional context**

**Comment by KaiKorla** [comment]
Hello @Grayfox2325,

thank you for this report. I could reproduce it and will take a look into.

**Comment by KaiKorla** [comment]
Fixed in v5.1.2
